---
title: "length_distributions"
author: "Chelsea Matthews"
date: "19 May 2020"
output: 
  html_document:
      code_folding: "show"
      number_sections: TRUE
      toc: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
											results = "asis",
											message = FALSE, warning = FALSE,
											error = FALSE)
```

```{r}
library(plyr)
library(tidyverse)
library(ggplot2)
library(grImport)
library(XML)
library(kableExtra)
library(cluster)
library(purrr)
library(data.table)
library(ggpubr)
library(scales)
library(viridis)
library(dplyr)
library(cowplot) 
library(egg) 
library(ggnewscale)
```



```{r}
length_dist_files <- dir("./length_distribution/raw_lengths", recursive=TRUE, full.names=TRUE, pattern=".txt$")
```


```{r}
#define colours
brightPurple <- "#65587F"
darkPurple <- "#463d58"
brightOrange <- "#F18867"
darkOrange <- "#A85F48"
brightGreen <- "#68c7d4"
darkGreen <- "#488b94"
otherGreen <- "green4"
darkotherGreen <- "darkgreen"

clr <- read.table(length_dist_files[[1]])
hifi_11_1 <- read.table(length_dist_files[[2]]) 
hifi_11_2 <- read.table(length_dist_files[[3]])
hifi_24 <- read.table(length_dist_files[[4]])

clr$V1 <- "CLR 30kb"
hifi_11_1$V1 <- "HiFi 11kb(1)"
hifi_11_2$V1 <- "HiFi 11kb(2)"
hifi_24$V1 <- "HiFi 24kb"

#join hifi dataframes together
hifi <- rbind(hifi_11_1,hifi_11_2,hifi_24)

hifi <- hifi[
  with(hifi, order(V1, V2)),]

hifi <- hifi %>%
  group_by(V1) %>%
  mutate(CumLength = cumsum(as.numeric(V2)))

hifi <- hifi %>%
  group_by() %>%
  mutate(Coverage = CumLength/387424359)

hifi <- hifi %>% group_by(V1) %>% mutate(id = row_number())

clr <- clr[
  with(clr, order(V1, V2)),]

clr <- clr %>%
  group_by(V1) %>%
  mutate(CumLength = cumsum(as.numeric(V2)))

clr <- clr %>%
  group_by() %>%
  mutate(Coverage = CumLength/387424359)

clr <- clr %>% group_by(V1) %>% mutate(id = row_number())
```

```{r}


a <- ggplot(clr) +
  geom_histogram(aes(x=V2, weight=V2/700000, fill = V1), binwidth=70) +
  scale_fill_manual(values=alpha(c(brightOrange), .7)) +
  geom_line(aes(x=V2, y=Coverage, group = V1, color = V1)) +
  scale_color_manual(values=c(darkOrange)) +
  scale_y_continuous(name = "~ Genome Coverage",
                     position = "right",
                     breaks = seq(0,180,20),
                     labels = label_number(suffix = "x"),
                     sec.axis = sec_axis(~.*387424359/1000000000,
                                         name = "Number of basepairs",
                                         labels = label_number(suffix = " Gbp", accuracy = 1),
                                         breaks = seq(0,70,10))) +
  xlab("Read Length") +
  theme_bw() +
  theme(legend.title = element_blank(),
        legend.position = "none") +
  scale_x_continuous(labels = label_number(suffix = " kbp",
                                           scale = (1/1000)))

ggsave("images/read_length_distribution/clr_read_length_dist.png",
         width = 4,
         height = 3.3,
         #units = c("in", "cm", "mm"),
         dpi = 300)

sets <- c("HiFi 11kb(1)","HiFi 11kb(2)")
dat11 <- subset(hifi, V1 %in% sets)

b <- ggplot(dat11) +
  geom_histogram(aes(x=V2, weight=V2/40000000, fill = V1), binwidth=70) +
  scale_fill_manual(values=alpha(c(brightGreen, otherGreen), .7)) +
  geom_line(aes(x=V2, y=Coverage, group = V1, color = V1)) +
  scale_color_manual(values=c(darkGreen, darkotherGreen)) +
  scale_y_continuous(name = "~ Genome Coverage",
                     position = "right",
                     breaks = seq(0,31,5),
                     labels = label_number(suffix = "x",
                                           accuracy = 1),
                     sec.axis = sec_axis(~.*387424359/1000000000,
                                         name = "Number of basepairs",
                                         labels = label_number(suffix = " Gbp", accuracy = 1),
                                         breaks = seq(0,12,2))) +
  xlab("Read Length") +
  theme_bw() +
  theme(legend.title = element_blank(),
        legend.position = "none") +
  scale_x_continuous(labels = label_number(suffix = " kbp",
                                           scale = (1/1000),
                                           accuracy = 1),
                     limits = c(0,50000))

ggsave("images/read_length_distribution/hifi11_read_length_dist.png",
         width = 4,
         height = 3.3,
         #units = c("in", "cm", "mm"),
         dpi = 300)

dat24 <- subset(hifi, V1 == "HiFi 24kb")

c <- ggplot(dat24) +
  geom_histogram(aes(x=V2, weight=V2/4000000, fill = V1), binwidth=70) +
  scale_fill_manual(values=alpha(c(brightPurple), .7)) +
  geom_line(aes(x=V2, y=Coverage, group = V1, color = V1)) +
  scale_color_manual(values=c(darkPurple)) +
  scale_y_continuous(name = "~ Genome Coverage",
                     position = "right",
                     breaks = seq(0,70,10),
                     labels = label_number(suffix = "x"),
                     sec.axis = sec_axis(~.*387424359/1000000000,
                                         name = "Number of basepairs",
                                         labels = label_number(suffix = " Gbp", accuracy = 1),
                                         breaks = seq(0,25,5))) +
  xlab("Read Length") +
  theme_bw() +
  theme(legend.title = element_blank(),
        legend.position = "none") +
  scale_x_continuous(labels = label_number(suffix = " kbp",
                                           scale = (1/1000)),
                     limits = c(0,50000))

ggsave("images/read_length_distribution/hifi24_read_length_dist.png",
         width = 4,
         height = 3.3,
         #units = c("in", "cm", "mm"),
         dpi = 300)

#Creating legend using a dummy plot
dat1 <- subset(hifi, V1 == "HiFi 11kb(1)")
dat2 <- subset(hifi,V1 == "HiFi 11kb(2)")
dummy <- rbind(head(dat1), head(dat2), head(dat24), head(clr))

dum <- ggplot(dummy) + 
  geom_histogram(aes(x=V2, weight=V2, fill = V1), binwidth=70) +
  scale_fill_manual(values=alpha(c(brightOrange, brightGreen, otherGreen, brightPurple), .7)) +
  theme_bw() +
  geom_line(aes(x=V2,y = Coverage*3000000, group = V1, color = V1)) +
  scale_y_continuous(name = "Number of bases\nincreasing →",
                     breaks=seq(0,5000000000,200000000),
                     sec.axis = sec_axis(~./3000000,
                                         name = "Coverage",
                                         breaks = seq(0,700000000,100000000),
                                         labels = label_number(suffix = "x"))) +
    scale_x_continuous(name = "CLR Length (kbp)",
                       labels = label_number(scale = (1/1000),
                                             accuracy = 1),
                       breaks = seq(0,70000,10000)) +
  theme(legend.position = "bottom")+
  scale_color_manual(values=c(darkOrange, darkGreen, darkotherGreen,darkPurple))

legend <- get_legend(
  dum +
    theme(legend.position = "bottom",
          legend.title = element_blank())
)


topSpace <- 0.5
bottomSpace <- 0.2
rightSpace <- 0.2
leftSpace <- 0.2

myPlot <- egg::ggarrange(a + theme(legend.position = "none",
                                   plot.margin = unit(c(topSpace, rightSpace, bottomSpace, leftSpace), "cm")),
                         b + theme(legend.position = "none",
                                   plot.margin = unit(c(topSpace, rightSpace, bottomSpace, leftSpace), "cm")),
                         c + theme(legend.position = "none",
                                   plot.margin = unit(c(topSpace, rightSpace, bottomSpace, leftSpace), "cm")),
                         heights = c(0.35,0.32,0.33),
                         labels = c("A - 30kb CLR","B - 11kb HiFi","C - 24kb HiFi"),
                         label.args = list(gp=gpar(fontface = "plain", fontfamily = "Simplex Roman")))

endPlot <- plot_grid(myPlot, legend, ncol = 1, rel_heights = c(1, .07))

ggsave("images/read_length_distribution/raw_read_length_dist_2.png",
         width = 5,
         height = 7.3,
         #units = c("in", "cm", "mm"),
         dpi = 300)
```



